// <auto-generated />
using System;
using LocadoraCarros.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocadoraCarros.Infra.Data.Migrations
{
    [DbContext(typeof(DbContextApplication))]
    [Migration("20230903111253_domingoManha")]
    partial class domingoManha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocadoraCarros.Domain.Entities.Aluguel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAluguel")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("carroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("carroId");

                    b.ToTable("Aluguel");
                });

            modelBuilder.Entity("LocadoraCarros.Domain.Entities.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<bool>("IsAlugado")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 1970,
                            IsAlugado = false,
                            Marca = "Volkswagen",
                            Modelo = "Fusca",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Ano = 1979,
                            IsAlugado = false,
                            Marca = "Volkswagen",
                            Modelo = "Kombi",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Ano = 1965,
                            IsAlugado = false,
                            Marca = "Ford",
                            Modelo = "Ford Mustang",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Ano = 1955,
                            IsAlugado = false,
                            Marca = "Fiat",
                            Modelo = "Fiat 600",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Ano = 1975,
                            IsAlugado = false,
                            Marca = "Volkswagen",
                            Modelo = "Brasília",
                            Status = 0
                        });
                });

            modelBuilder.Entity("LocadoraCarros.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("LocadoraCarros.Domain.Entities.Aluguel", b =>
                {
                    b.HasOne("LocadoraCarros.Domain.Entities.Carro", "Carro")
                        .WithMany("Alugueis")
                        .HasForeignKey("carroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("LocadoraCarros.Domain.Entities.Carro", b =>
                {
                    b.Navigation("Alugueis");
                });
#pragma warning restore 612, 618
        }
    }
}
